kind = "mobile"
previewPath = "/"
title = "Video Vault"
version = "1.0.0"
id = "artifacts/video-vault"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 21545

[services.development]
run = "pnpm --filter @workspace/video-vault run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/video-vault", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/video-vault", "run", "serve" ]

[services.env]
PORT = "21545"
BASE_PATH = "/"
